[package]
name = "learning-bellman-groth16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.13.1"
ff = "0.12"
group = "0.12"
pairing = "0.22"
rand_core = "0.6"
subtle = "2.2.1"
